// Release URLs are generated by npm run version:sync from version.js.
importScripts("./version.js?v=1.10.0");
const CACHE = `face-me-v${globalThis.FACE_ME_VERSION}`;
const ASSETS = [
  "./",
  "./index.html",
  "./styles.css?v=1.10.0",
  "./app.js?v=1.10.0",
  "./core.js?v=1.10.0",
  "./lifecycle.js?v=1.10.0",
  "./device-services.js?v=1.10.0",
  "./orientation-service.js?v=1.10.0",
  "./famous-locations.js?v=1.10.0",
  "./version.js?v=1.10.0",
  "./manifest.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png"
];

self.addEventListener("install", event => {
  event.waitUntil(caches.open(CACHE)
    .then(cache => cache.addAll(ASSETS.map(url => new Request(url, { cache: "reload" }))))
    .then(() => self.skipWaiting()));
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(key => key.startsWith("face-me-") && key !== CACHE).map(key => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", event => {
  if (event.request.method !== "GET" || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(
    fetch(event.request, { cache: "no-cache" })
      .then(response => {
        if (response.ok) {
          const clone = response.clone();
          event.waitUntil(caches.open(CACHE).then(cache => cache.put(event.request, clone)).catch(() => {}));
        }
        return response;
      })
      .catch(async () => {
        const cache = await caches.open(CACHE);
        const cached = await cache.match(event.request);
        if (cached) return cached;
        if (event.request.mode === "navigate") return (await cache.match("./index.html")) || Response.error();
        return Response.error();
      })
  );
});
